nelmio_api_doc:
    documentation:
        info:
            title: SharelocAPI
            description: Web service de l'application ShareLoc créer lors de la licence CDAD 
            version: 0.0.2
    areas: # to filter documented areas
        path_patterns:
            - ^/api/user
            - ^/api/login
            - ^/api/whoami
            - ^/api/collocation
            - ^/api/invitation
            - ^/api/service
            - ^/api/message
