nelmio_api_doc:
    documentation:
        info:
            title: SharelocAPI
            description: Web service de l'application ShareLoc créer lors de la licence CDAD 
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api/user # Accepts routes under /api except /api/doc
            - ^/api/collocation # Accepts routes under /api except /api/doc
            - ^/api/invitation # Accepts routes under /api except /api/doc
