nelmio_api_doc:
    documentation:
        info:
            title: SharelocAPI
            description: Web service de l'application ShareLoc créer lors de la licence CDAD 
            version: 1.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/user
            - ^/api/login
            - ^/api/register
            - ^/api/whoami
            - ^/api/collocation
            - ^/api/invitation
            - ^/api/service
            - ^/api/message
